bussines/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_views.home, name='home'),
    path('manager-signup/', home_views.manager_signup, name='manager_signup'),
    path('private-signup/', home_views.private_signup, name='private_signup'),
    path('about/', home_views.about, name='about'),
    path('services/', home_views.services, name='services'),
    path('accounts/login/', home_views.login_view, name='login_view'),
    path('manager/', include('manager.urls', namespace='manager')),
    path('worker/', include('worker.urls', namespace='worker')),
    path('private/', include('private.urls')),
    
]

worker/urls.py
from django.urls import path
from . import views

app_name='worker'

urlpatterns = [
    path('worker_dashboard/', views.worker_dashboard, name='worker_dashboard'),
    path('register-item', views.register_item, name='register_item'),
    path('fill-report',views.fill_report,name='fill_report'),
    path('daily-expenditure/<int:branch_id>', views.daily_expenditure, name='daily_expenditure'),
    path('update-item/<int:item_id>', views.update_item, name='update_item'),
    path('delete-item/<int:item_id>', views.delete_item, name='delete_item'),
]

worker/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Group,Permission
from manager.models import Branch
from django.utils import timezone

class Worker(AbstractUser):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='workers')
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    # Add other fields if necessary
    groups = models.ManyToManyField(
        Group,
        related_name='worker_set',  # Changed from 'user_set' to 'worker_set'
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='worker_user_permissions',  # Changed from 'user_set' to 'worker_user_permissions'
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )

    def manager_name(self):
        return self.branch.manager.username if self.branch and self.branch.manager else 'No Manager'
    
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.branch.name})"
    class Meta:
        verbose_name = 'Worker'
        verbose_name_plural = 'Workers'    
  
class Item(models.Model):
    name = models.CharField(max_length=100)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class ItemReport(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    laststock = models.IntegerField(default=0)
    addedstock = models.IntegerField(default=0)
    currentstock = models.IntegerField(default=0)
    consumed = models.IntegerField(default=0)
    remaining = models.IntegerField(default=0)
    incomespent = models.FloatField(default=0)
    incomegained = models.FloatField(default=0)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"Report for {self.item.name} on {self.date}"
    
class DailyExpenditure(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    expenditure = models.FloatField()

    class Meta:
        unique_together = ('branch', 'date')

    def __str__(self):
        return f"{self.branch.name} - {self.date}: {self.expenditure}"    

worker/forms.py
from django import forms
from .models import Worker,ItemReport,Item, DailyExpenditure
from django.forms import modelformset_factory

class WorkerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Worker
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'branch']

class ItemRegistrationForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name']  # Assuming 'name' is the field to be filled by the worker

ItemFormSet= modelformset_factory(Item, form=ItemRegistrationForm, extra=1)    

class ItemForm(forms.ModelForm):
    class Meta:
        model = ItemReport
        fields = ['item', 'laststock', 'addedstock', 'currentstock', 'consumed', 'remaining', 'incomespent', 'incomegained']

class ItemUpdateForm(forms.ModelForm):
    class Meta:
        model = ItemReport
        fields = [ 'laststock', 'addedstock', 'currentstock', 'consumed', 'remaining', 'incomespent', 'incomegained']     

    def __init__(self, *args, **kwargs):
        worker = kwargs.pop('worker', None)
        super().__init__(*args, **kwargs)
        if worker:
            self.fields['item'].queryset = Item.objects.filter(worker=worker)

class DailyExpenditureForm(forms.ModelForm):
    class Meta:
        model = DailyExpenditure
        fields = ['date', 'expenditure']            

worker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Worker,Item, ItemReport
from .forms import  ItemForm,ItemRegistrationForm,ItemUpdateForm, DailyExpenditureForm
from django.contrib.auth.decorators import login_required
import logging
from django.utils import timezone
from django.http import HttpResponse
from django.forms import modelformset_factory
from manager.models import Branch

logger=logging.getLogger(__name__)


@login_required
def worker_dashboard(request):
    worker = request.user
    if not isinstance(worker, Worker):
        logger.error("Current user is not a worker: %s", worker)
        return HttpResponse("User is not a worker")
    items = Item.objects.filter(worker=worker)  # Filter items by the logged-in worker
    reports=ItemReport.objects.filter(item__worker=worker)
    branch=worker.branch
    latest_reports = []
    daily_reports = []

    if 'latest_reports' in request.GET:
        for item in items:
            try:
                latest_report = ItemReport.objects.filter(item=item).latest('date')
                latest_reports.append(latest_report)
            except ItemReport.DoesNotExist:
                continue  # Skip if no report exists for this item

    if 'daily_reports' in request.GET:
        daily_reports = ItemReport.objects.filter(item__worker=worker).order_by('-date')
    else:
        daily_reports = None

    return render(request, 'worker_dashboard.html', {
        'reports':reports,
        'items': items,
        'latest_reports': latest_reports,
        'daily_reports': daily_reports,
        'branch':branch
    })

@login_required
def register_item(request):
    ItemFormSet = modelformset_factory(Item, form=ItemRegistrationForm, extra=1)
    if request.method == 'POST':
        formset = ItemFormSet(request.POST, queryset=Item.objects.none())
        if formset.is_valid():
            for form in formset:
                item = form.save(commit=False)
                item.worker = request.user
                item.save()
            return redirect('worker:worker_dashboard')
    else:
        formset = ItemFormSet(queryset=Item.objects.none())
    
    return render(request, 'register_item.html', {'formset': formset})

@login_required
def fill_report(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.item.worker = request.user  # Assign the item's worker as the logged-in user
            report.date=timezone.now()
            report.save()
            return redirect('worker:fill_report')
    else:
        # Filter items based on the logged-in worker
        items = Item.objects.filter(worker=request.user)

        item_id = request.GET.get('item_id')
        if item_id:
            item = get_object_or_404(Item, pk=item_id)
            last_report = ItemReport.objects.filter(item=item).order_by('-date').first()
            reports = ItemReport.objects.filter(item=item).order_by('-date')
            
            if last_report:
                # Initialize the form with the last report's remaining value as laststock
                form = ItemForm(initial={'item': item, 'laststock': last_report.remaining})
            else:
                form = ItemForm(initial={'item': item})
        else:
            item = None
            last_report = None
            reports = None
            form = ItemForm()  # Initialize form without specific item

    return render(request, 'fill_report.html', {'form': form, 'items': items, 'last_report': last_report, 'reports': reports})

@login_required
def daily_expenditure(request, branch_id):
    branch = get_object_or_404(Branch, id=branch_id)
    if request.method == 'POST':
        form = DailyExpenditureForm(request.POST)
        if form.is_valid():
            daily_expenditure = form.save(commit=False)
            daily_expenditure.branch = branch
            daily_expenditure.save()
            return redirect('worker:worker_dashboard')
    else:
        form = DailyExpenditureForm()

    return render(request, 'daily_expenditure.html', {'form': form, 'branch': branch})

@login_required
def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == 'POST':
        form = ItemUpdateForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('worker:worker_dashboard')
    else:
        form = ItemUpdateForm(instance=item)
    return render(request, 'update_item.html', {'form': form, 'item': item})

@login_required
def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('worker:worker_dashboard')
    return render(request, 'delete_item.html', {'item': item})

worker/templates/daily_expenditure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Record Daily Expenditure</title>
</head>
<body>
    <h2>Record Daily Expenditure for {{ branch.name }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

worker/templates/delete_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Item</title>
</head>
<body>
    <h1>Are you sure you want to delete {{ item.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
    </form>
</body>
</html>

worker/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{mesagge}}</p>
</body>
</html>

worker/templates/fill_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Item</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Fill Report</h1>

    {% if last_report %}
    <h2>Last Report</h2>
    <table>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Last Stock</td>
            <td>{{ last_report.laststock }}</td>
        </tr>
        <tr>
            <td>Present</td>
            <td>{{ last_report.addedstock }}</td>
        </tr>
        <tr>
            <td>Consumed</td>
            <td>{{ last_report.currentstock }}</td>
        </tr>
        <tr>
            <td>Entered</td>
            <td>{{ last_report.consumed }}</td>
        </tr>
        <tr>
            <td>Remaining</td>
            <td>{{ last_report.remaining }}</td>
        </tr>
        <tr>
            <td>Income Spent</td>
            <td>{{ last_report.incomespent }}</td>
        </tr>
        <tr>
            <td>Income Gained</td>
            <td>{{ last_report.incomegained }}</td>
        </tr>
    </table>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
            {% for field in form %}
            <tr>
                <td>{{ field.label }}</td>
                <td>{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit">Submit</button>
    </form>
    <a href="{%url 'worker:worker_dashboard'%}">Back To Dashboard</a>
</body>
</html>

worker/templates/register_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Item</title>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const formContainer = document.querySelector('#form-container');
            const addButton = document.querySelector('#add-form');
            const totalForms = document.querySelector('#id_form-TOTAL_FORMS');

            addButton.addEventListener('click', function() {
                const currentFormCount = formContainer.children.length;
                const newForm = formContainer.children[0].cloneNode(true);
                const regex = new RegExp(`form-(\\d){1}-`, 'g');

                newForm.innerHTML = newForm.innerHTML.replace(regex, `form-${currentFormCount}-`);
                formContainer.appendChild(newForm);
                totalForms.value = parseInt(totalForms.value) + 1;
            });
        });
    </script>
</head>
<body>
    <h2>Register Items</h2>
    <form method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        <div id="form-container">
            {% for form in formset %}
                <div>{{ form.as_p }}</div>
            {% endfor %}
        </div>
        <button type="button" id="add-form">Add Another Item</button>
        <button type="submit">Register</button>
    </form>
</body>
</html>

worker/templates/update_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Item</title>
</head>
<body>
    <h1>Update Item - {{ item.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Item</button>
    </form>
</body>
</html>

worker/templates/worker_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Worker Dashboard</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
        .button-container {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <h1>Worker Dashboard</h1>
    <a href="{%url 'home'%}">HOME</a>
    
    <div class="button-container">
        <a href="?latest_reports=true"><button>Show Latest Info</button></a>
        <a href="?daily_reports=true"><button>Show Day-to-Day Info</button></a>
    </div>

    <a href="{% url 'worker:register_item' %}"><button>REGISTER ITEM</button></a>

    <h2>Items</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for item in items %}
        <tr>
            <td>{{ item.name }}</td>
            <td><a href="{% url 'worker:update_item' item.id %}"><button>UPDATE</button></a></td>
            <td><a href="{% url 'worker:delete_item' item.id %}"><button>DELETE</button></a></td>
        </tr>
        {% endfor %}
    </table>

    <a href="{% url 'worker:fill_report' %}"><button>Fill Report</button></a>
    <a href="{% url 'worker:daily_expenditure' branch.id %}"><button>Record Daily Expenditure</button></a>
    
    {% if latest_reports %}
    <h2>Latest Reports</h2>
    <table>
        <tr>
            <th>Item</th>
            <th>Date</th>
            <th>Last Stock</th>
            <th>AddedStock</th>
            <th>Currentstock</th>
            <th>Consumed</th>
            <th>Remaining</th>
            <th>Income Spent</th>
            <th>Income Gained</th>
            
        </tr>
        {% for report in latest_reports %}
        <tr>
            <td>{{ report.item.name }}</td>
            <td>{{ report.date }}</td>
            <td>{{ report.laststock }}</td>
            <td>{{ report.addedstock }}</td>
            <td>{{ report.currentstock }}</td>
            <td>{{ report.consumed }}</td>
            <td>{{ report.remaining }}</td>
            <td>{{ report.incomespent }}</td>
            <td>{{ report.incomegained }}</td>
            
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    
    {% if daily_reports %}
    <h2>Day-to-Day Reports</h2>
    <table>
        <tr>
            <th>Item</th>
            <th>Date</th>
            <th>Last Stock</th>
            <th>Present</th>
            <th>Consumed</th>
            <th>Entered</th>
            <th>Remaining</th>
            <th>Income Spent</th>
            <th>Income Gained</th>
            
        </tr>
        {% for report in daily_reports %}
        <tr>
            <td>{{ report.item.name }}</td>
            <td>{{ report.date }}</td>
            <td>{{ report.laststock }}</td>
            <td>{{ report.present }}</td>
            <td>{{ report.consumed }}</td>
            <td>{{ report.entered }}</td>
            <td>{{ report.remaining }}</td>
            <td>{{ report.incomespent }}</td>
            <td>{{ report.incomegained }}</td>
            
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>